org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : r4 = $r7 >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r8 = <org.apache.zeppelin.socket.NotebookServer: org.slf4j.Logger LOG>
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r8 = <org.apache.zeppelin.socket.NotebookServer: org.slf4j.Logger LOG> >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : interfaceinvoke $r8.<org.slf4j.Logger: void error(java.lang.String,java.lang.Throwable)>("Exception from run", r4)
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : interfaceinvoke $r8.<org.slf4j.Logger: void error(java.lang.String,java.lang.Throwable)>("Exception from run", r4) >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r9 = new org.apache.zeppelin.notebook.socket.Message
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r9 = new org.apache.zeppelin.notebook.socket.Message >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r5 = <org.apache.zeppelin.notebook.socket.Message$OP: org.apache.zeppelin.notebook.socket.Message$OP ERROR_INFO>
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r5 = <org.apache.zeppelin.notebook.socket.Message$OP: org.apache.zeppelin.notebook.socket.Message$OP ERROR_INFO> >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : specialinvoke $r9.<org.apache.zeppelin.notebook.socket.Message: void <init>(org.apache.zeppelin.notebook.socket.Message$OP)>($r5)
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : specialinvoke $r9.<org.apache.zeppelin.notebook.socket.Message: void <init>(org.apache.zeppelin.notebook.socket.Message$OP)>($r5) >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r10 = virtualinvoke $r9.<org.apache.zeppelin.notebook.socket.Message: org.apache.zeppelin.notebook.socket.Message put(java.lang.String,java.lang.Object)>("info", "Oops! There is something wrong with the notebook file system. Please check the logs for more details.")
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r10 = virtualinvoke $r9.<org.apache.zeppelin.notebook.socket.Message: org.apache.zeppelin.notebook.socket.Message put(java.lang.String,java.lang.Object)>("info", "Oops! There is something wrong with the notebook file system. Please check the logs for more details.") >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r11 = virtualinvoke r0.<org.apache.zeppelin.socket.NotebookServer: java.lang.String serializeMessage(org.apache.zeppelin.notebook.socket.Message)>($r10)
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r11 = virtualinvoke r0.<org.apache.zeppelin.socket.NotebookServer: java.lang.String serializeMessage(org.apache.zeppelin.notebook.socket.Message)>($r10) >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : virtualinvoke r1.<org.apache.zeppelin.socket.NotebookSocket: void send(java.lang.String)>($r11)
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : virtualinvoke r1.<org.apache.zeppelin.socket.NotebookSocket: void send(java.lang.String)>($r11) >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : return 0
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r6 = virtualinvoke r3.<org.apache.zeppelin.notebook.Paragraph: org.apache.zeppelin.user.AuthenticationInfo getAuthenticationInfo()>() >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : virtualinvoke r2.<org.apache.zeppelin.notebook.Note: void persist(org.apache.zeppelin.user.AuthenticationInfo)>($r6)
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r6 = virtualinvoke r3.<org.apache.zeppelin.notebook.Paragraph: org.apache.zeppelin.user.AuthenticationInfo getAuthenticationInfo()>() >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r7 := @caughtexception
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : virtualinvoke r2.<org.apache.zeppelin.notebook.Note: void persist(org.apache.zeppelin.user.AuthenticationInfo)>($r6) >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $z0 = 1
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : virtualinvoke r2.<org.apache.zeppelin.notebook.Note: void persist(org.apache.zeppelin.user.AuthenticationInfo)>($r6) >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r7 := @caughtexception
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $z0 = 1 >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : return $z0
org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $z0 = 1 >>>>>>>> org.apache.zeppelin.socket.NotebookServer.persistNoteWithAuthInfo : $r7 := @caughtexception
